
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FluidCursor from "./cursor";
import ReactLenis from "lenis/react";
import "@radix-ui/themes/styles.css";
import Navbar from "@/components/Navbar";

// import SmoothScrollWrapper from "@/lenis";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased cursorr`}
      >
        {/* <SmoothScrollWrapper> */}
        <ReactLenis root>
        <div className="">
       
        {children }
          
        </div>
        </ReactLenis>
        {/* </SmoothScrollWrapper> */}
        {/* <FluidCursor /> */}
      </body>
    </html>
  );
}
